### ISSUE TITLE
Show Attack/Defence Values on Equipped Gear

### ISSUE THREAD

**Issue by UrbanMonkey** [GeekyEggo/DestinyTailor#1]
Mostly needed for armour defense values to show where gains can be made in stat values from infusing higher level gear.

**Comment by GeekyEggo** [comment]
This has now been introduced and in visible on items, when viewing on larger displays (non-mobile).

**Comment by GeekyEggo** [comment]
https://github.com/GeekyEggo/DestinyTailor/commit/f480aed51342bfeb0b514260114b26da56492293
