### ISSUE TITLE
Can't fetch character

### ISSUE THREAD

**Issue by AvianAzure** [GeekyEggo/DestinyTailor#11]
I apologise if this isn't the correct place for this, only way I could find of contact. When I try to use this on your site it gets stuck at"Fetching Character" when I click on one. I've had friends test this with their accounts and under the same circumstances. The issue only occurs with my account. Even when others try it on their own devices.

**Comment by GeekyEggo** [comment]
I've just released a fix that coincides with AoT; hopefully this should resolve any issues you were having. Give it a go and let me know! :)

**Comment by AvianAzure** [comment]
Works now, cheers!
