### ISSUE TITLE
Duplicate XBox gamer tags

### ISSUE THREAD

**Issue by GeekyEggo** [GeekyEggo/DestinyTailor#3]
When searching for an XBox gamertag, an error is thrown when there are multiple matching tags, e.g. searching for "high im drugs" returns 2 memberships, "High Im Drugs" and "High im Drugs", one of which is inactive.

**Comment by SunburnedGoose** [comment]
This has happened with DIM in the past when searching for users. I'll have
to look at how we differentiated

**Comment by GeekyEggo** [comment]
`/SearchDestinyPlayer/` is returning duplicate results, although when requesting the account summary information for both of them via their membership id, the incorrect one is giving:
`{
  "ErrorCode": 1618,
  "ThrottleSeconds": 0,
  "ErrorStatus": "DestinyUnexpectedError",
  "Message": "An unexpected error has occurred while trying to grab Destiny information.  Let us know if you see this.",
  "MessageData": {}
}`

I can't seem to find any flags on the search to indicate an inactive account? Is it simply a case of hitting each summary to check if its still valid?

**Comment by SunburnedGoose** [comment]
Yeah.  What happens is a user must of had the account in the past, changed the gamertag, and never played Destiny again with the account.  Later, a new gamertag was created with the name, and they played Destiny.  Now there are two Destiny accounts :/

**Comment by SunburnedGoose** [comment]
https://www.bungie.net/en/Forums/Post/204594149?page=0&sort=0&showBanned=0&path=1

**Comment by v-fedorov** [comment]
I posted this on slack a little while ago :)

According to him it most likely was caused by a forced name change from Xbox.

Just to be safe we did Response[Response.length - 1] since the 2nd id listed was the current
