### ISSUE TITLE
Crashes on sparrow horn

### ISSUE THREAD

**Issue by tantalor** [GeekyEggo/DestinyTailor#9]
Here we create an Item for each equippable,
https://github.com/GeekyEggo/DestinyTailor/blob/a7dee9c9eb2482ed24a8658a391dc6ab3b85a4f6/client/js/services/inventoryService.js#L45

And the equippable is required to have at least one item,
https://github.com/GeekyEggo/DestinyTailor/blob/a7dee9c9eb2482ed24a8658a391dc6ab3b85a4f6/client/js/models/item.js#L20

But on my character (psn:tantalor, Hunter) I have a sparrow horn (buckethash:3796357825) that has no items, and crashes the app in item.js

**Comment by GeekyEggo** [comment]
Hey @tantalor, thanks for raising this! I believe it's related to classified items; I've got a hotfix incoming, should be available shortly.

**Comment by GeekyEggo** [comment]
Hopefully this should all be sorted now; [psn/tantalor/hunter](http://destinytailor.com/psn/tantalor/hunter). Any problems, just let me know. 😄

**Comment by tantalor** [comment]
THANKS 😀 😄
